version: '3.4'

services:
  web:
    image: registry.gitlab.com/addapp/django-podify
    build: ./web/
    env_file:
      - .env.dockerdev
    volumes:
      - uwsgi_data:/code/uwsgi
      - media:/code/media
      - static:/code/static
      - db:/code/db
  redis:
    image: redis:7
  nginx:
    image: nginx:stable
    volumes:
      - uwsgi_data:/tmp/uwsgi
      - media:/var/www/podify/media
      - static:/var/www/podify/static
      - ./nginx.conf:/etc/nginx/conf.d/podify.conf:ro
    ports:
      - "8000:8000"
    depends_on:
      - web
volumes:
  uwsgi_data:
  media:
  static:
  db: