version: '3.4'

services:
  web:
    image: podify:latest
    env_file:
      - .env.prod
    ports:
      - "8000:8000"
    networks:
      - default
      - podify_net
  redis:
    image: redis:5.0.8
    networks:
      - default
networks:
  podify_net:
    external:
      name: podify_net
