version: '3.4'

services:
  web:
    image: registry.gitlab.com/addapp/django-podify:v1.4.4
    env_file:
      - .env.prod
    ports:
      - "8000:8000"
    volumes:
      - podify_db:/code/db
      - podify_media:/code/media
  redis:
    image: redis:5.0.8
volumes:
  podify_db:
  podify_media:
  
