# Generated by Django 2.1.5 on 2019-02-11 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0003_auto_20190211_0042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episode',
            old_name='mp3_file',
            new_name='mp3',
        ),
    ]
