# Generated by Django 2.1.5 on 2019-02-12 19:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0011_auto_20190212_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name='episode',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
