# Generated by Django 2.1.5 on 2019-02-12 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0012_auto_20190212_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='slug',
            field=models.CharField(editable=False, max_length=100, unique=True),
        ),
    ]
