# Generated by Django 2.1.5 on 2019-02-13 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0014_auto_20190212_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
