# Generated by Django 2.1.5 on 2019-02-13 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0017_auto_20190213_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='downloaded',
        ),
    ]
