# Generated by Django 2.1.5 on 2019-02-16 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0020_auto_20190215_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
