# Generated by Django 2.1.5 on 2019-02-17 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0021_episode_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='image',
            field=models.ImageField(blank=True, upload_to='thumbnails'),
        ),
        migrations.AddField(
            model_name='episode',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
    ]
