# Generated by Django 2.1.5 on 2019-03-02 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0026_remove_episode_playlist_episode'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='image',
            field=models.ImageField(blank=True, upload_to='thumbnails'),
        ),
    ]
