# Generated by Django 2.1.5 on 2019-03-03 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0027_episode_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='mp3_source',
            field=models.FilePathField(allow_files=False, allow_folders=True, blank=True),
        ),
    ]
