# Generated by Django 2.1.5 on 2019-03-03 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0028_podcast_mp3_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcast',
            name='mp3_source',
        ),
    ]
