# Generated by Django 2.1.5 on 2019-03-03 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0029_remove_podcast_mp3_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='video_id',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
    ]
