# Generated by Django 3.0.5 on 2020-04-03 19:24

from django.db import migrations, models

import podcasts.models


class Migration(migrations.Migration):
    dependencies = [
        ('podcasts', '0031_episode_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='image',
            field=models.ImageField(blank=True, upload_to=podcasts.models.podcast_media_path),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='image',
            field=models.ImageField(blank=True, upload_to=podcasts.models.podcast_media_path),
        ),
    ]
