# Generated by Django 3.0.5 on 2020-04-03 19:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('podcasts', '0034_auto_20200403_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='video_id',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
