# Generated by Django 3.0.5 on 2020-04-03 19:49

from django.db import migrations, models

import podcasts.models


class Migration(migrations.Migration):
    dependencies = [
        ('podcasts', '0035_auto_20200403_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='image',
            field=models.ImageField(blank=True, upload_to=podcasts.models.episode_media_path),
        ),
    ]
