# Generated by Django 3.0.5 on 2020-04-03 21:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('podcasts', '0036_auto_20200403_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
    ]
