# Generated by Django 3.0.5 on 2020-04-06 16:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('podcasts', '0039_auto_20200406_1738'),
    ]

    def generate_update_schedule(apps, schema_editor):
        from django_q.tasks import schedule

        schedule('django.core.management.call_command', 'background_sync', '--download',
                 name='Sync all podcasts',
                 schedule_type='D',
                 repeats=-1,
                 )

    operations = [
        migrations.RunPython(generate_update_schedule),
    ]