# Generated by Django 3.0.5 on 2020-04-07 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0040_auto_20200406_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
