# Generated by Django 4.1 on 2022-08-12 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0041_auto_20200407_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='downloaded',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='updated',
        ),
        migrations.AddField(
            model_name='episode',
            name='initialized',
            field=models.BooleanField(default=False, help_text='Whether the episode metadata & mp3 are present.'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='invalid',
            field=models.BooleanField(default=False, help_text='Whether there was an error with the episode. The episode will be disregarded in future operations.'),
        ),
    ]
