# Generated by Django 4.1 on 2022-08-16 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0043_alter_episode_id_alter_podcast_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='from_playlist',
            field=models.BooleanField(
                default=False, help_text="Whether the episode is from the podcast's playlist."),
        ),
    ]
