# Generated by Django 2.1.5 on 2019-02-04 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcast',
            name='type',
        ),
        migrations.AddField(
            model_name='podcast',
            name='podcast_type',
            field=models.CharField(choices=[('YTP', 'YouTube Playlist'), ('SNG', 'Single Videos')], default='YTP', max_length=3),
        ),
        migrations.AddField(
            model_name='podcast',
            name='title',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
    ]
