# Generated by Django 2.1.5 on 2019-02-12 14:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0005_auto_20190211_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name='episode',
            name='pub_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='podcast',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='podcast',
            name='image',
            field=models.ImageField(blank=True, upload_to='thumbnails'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='mp3',
            field=models.FileField(blank=True, upload_to=None),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
