# Generated by Django 2.1.5 on 2019-02-12 19:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0007_auto_20190212_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0), editable=False),
        ),
        migrations.AlterField(
            model_name='episode',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='episode',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='slug',
            field=models.CharField(max_length=100),
        ),
    ]
