# Generated by Django 2.1.5 on 2019-02-12 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0008_auto_20190212_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='mp3',
            field=models.FileField(blank=True, editable=False, upload_to=None),
        ),
    ]
