# Generated by Django 2.1.5 on 2019-02-12 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0013_auto_20190212_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='slug',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
