# Generated by Django 2.1.5 on 2019-02-13 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0016_auto_20190213_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='mp3',
            field=models.FileField(blank=True, upload_to='mp3s'),
        ),
    ]
