# Generated by Django 2.1.5 on 2019-02-17 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0022_auto_20190217_0121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='image',
        ),
        migrations.AddField(
            model_name='episode',
            name='video_id',
            field=models.CharField(blank=True, max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
