# Generated by Django 2.1.5 on 2019-02-17 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0023_auto_20190217_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='downloaded',
            field=models.BooleanField(default=False),
        ),
    ]
