# Generated by Django 2.1.5 on 2019-02-21 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0024_episode_downloaded'),
    ]

    operations = [
        migrations.RenameField(
            model_name='podcast',
            old_name='url',
            new_name='playlist_url',
        ),
        migrations.RemoveField(
            model_name='podcast',
            name='podcast_type',
        ),
        migrations.AddField(
            model_name='episode',
            name='invalid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='episode',
            name='playlist_episode',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='episode',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
    ]
