# Generated by Django 3.0.5 on 2020-04-03 19:24

from django.db import migrations, models

import podcasts.models


class Migration(migrations.Migration):
    dependencies = [
        ('podcasts', '0033_auto_20200403_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='mp3',
            field=models.FileField(blank=True, upload_to=podcasts.models.episode_media_path),
        ),
    ]
